### ISSUE TITLE
Helm dependency

### ISSUE THREAD

**Issue by technician77** [galdor/rfc-mode#2]
Would it be much of a hassle write this without the use of helm?

**Comment by galdor** [comment]
Sorry for the lack of response, I did not receive any notification about your message.

This mode was originally written with Helm in mind, so the browser is going to require Helm at least until Emacs specifies a generic "browser" mechanism.

However I'm going to release a new version which makes Helm optional, making it possible to use `rfc-mode-read` without installing Helm.

**Comment by technician77** [comment]
Thanks for the effort, though it didn't turn out as I thought. First, I'm not a programmer an I use use-package. If I install rfc-mode via use-package it still pulls in helm and its dependencies. Deleting via package manager seems impossible since it sees helm as a dependency of rfc-mode.

**Comment by galdor** [comment]
On 2020-02-15 16:58, Jens Lange wrote:
> Thanks for the effort, though it didn't turn out as I thought. First, I'm not a programmer an I use use-package. If I install rfc-mode via use-package it still pulls in helm and its dependencies. Deleting via package manager seems impossible since it sees helm as a dependency of rfc-mode.

Infortunately the Emacs package does not have the concept of optional
dependency, so Helm has to be declared as dependency for the general case. The
good news is that it does not really matter since you do not have to actually
load Helm. It will be installed locally but inactive, and you will be able to
use rfc-mode-read.

-- 
Nicolas Martyanoff
http://snowsyn.net
khaelin@gmail.com
