### ISSUE TITLE
use page break line mode

### ISSUE THREAD

**Issue by kaiwk** [galdor/rfc-mode#7]
i found there are some '^L' characters to indicate page breaks in rfc-mode, this package [page-break-lines](https://github.com/purcell/page-break-lines) can turn these characters into a real line.

**Comment by galdor** [comment]
In rfc-mode, we display both the footer and the header at the top of the buffer because there is no guarantee that the window is heigh enough for the footer to be visible. Therefore displaying an horizontal line between the first and third line would look strange.

Thank you for telling me about this package though, I'll keep it in mind for other use cases :)
